"""followers

Revision ID: 28a0b8995693
Revises: 39cdf8b9f42a
Create Date: 2020-11-26 18:27:00.721442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a0b8995693'
down_revision = '39cdf8b9f42a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user2.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user2.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
