"""new fields in user model

Revision ID: 39cdf8b9f42a
Revises: bcda7527dc80
Create Date: 2020-11-26 08:33:28.779556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39cdf8b9f42a'
down_revision = 'bcda7527dc80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user2', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user2', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user2', 'last_seen')
    op.drop_column('user2', 'about_me')
    # ### end Alembic commands ###
